### PR TITLE
release version 0.2.0

### PR DESCRIPTION
**Pull request by davidtwco**
Includes all changes since a59b8ee82:

7e76f9d Use hashbrown
cfc9c7d Reduce the number of reallocations for PackageStringTable::data
0ecb11d Avoid extra HashMap in PackageStringTable
12660a7 Change assert to debug_assert in PackageStringTable
cf41f62 Handle entries with differing columns
cf21bfb Update object dependency
025395b update repository links and readme

### CODE REVIEW

**Comment by philipc** [comment]
Note that because `object` is part of the public API, any breaking changes in it automatically become breaking changes in thorin (such as the bump from `object` 0.27 to 0.28). (`gimli` is part of the public API too (via `Error`), but wasn't updated this time.)

**Comment by davidtwco** [comment]
I can publish this release locally, but can't merge this without someone else with write privileges approving it.

**Comment by Mark-Simulacrum** [comment]
Based on @philipc's comment it sounds like we should bump to 0.2, not 0.1.2, right? Since this is a breaking change due to the object crate bump?

**Comment by davidtwco** [comment]
> Based on @philipc's comment it sounds like we should bump to 0.2, not 0.1.2, right? Since this is a breaking change due to the object crate bump?

Of course, apologies, fixed that, a little jet-lagged yesterday.

**Review by Mark-Simulacrum — APPROVED** [review]

**Comment by Mark-Simulacrum** [comment]
Feel free to merge when ready.

**Pull request merged**
